In [43]:
import numpy as np


J = np.random.rand(3,5)
tau = np.random.rand(5)
f= np.random.rand(3)

In [44]:
tau = J.T@f 
print(f,tau)

[0.15374924 0.48525895 0.92958357] [0.87934258 0.95470206 0.36657353 0.70595557 0.46116295]


In [45]:
print("f:",f)
print(J@tau)
print(np.linalg.pinv(J.T)@tau)

f: [0.15374924 0.48525895 0.92958357]
[1.44820261 1.95639741 1.46097751]
[0.15374924 0.48525895 0.92958357]


In [49]:
J.T@np.linalg.pinv(J.T)

array([[ 0.59147055,  0.22639844, -0.29361674,  0.31757947,  0.05752721],
       [ 0.22639844,  0.84896175,  0.12582537, -0.21858373,  0.11557929],
       [-0.29361674,  0.12582537,  0.73575523,  0.1668135 ,  0.25406676],
       [ 0.31757947, -0.21858373,  0.1668135 ,  0.68219904,  0.2008512 ],
       [ 0.05752721,  0.11557929,  0.25406676,  0.2008512 ,  0.14161344]])

In [50]:
J@J.T

array([[1.22299014, 1.03557118, 0.81504089],
       [1.03557118, 1.75074009, 1.01939929],
       [0.81504089, 1.01939929, 0.9046986 ]])

In [78]:
u1,s1,v1 = np.linalg.svd(J)
print(u1)
print("s:",s1, "1/s:", 1/s1)
print(v1)

[[-0.53989692  0.76617455 -0.34855109]
 [-0.68975996 -0.64004021 -0.33849627]
 [-0.48243395  0.05766349  0.87403227]]
s: [1.80950425 0.6474913  0.42997466] 1/s: [0.55263755 1.5444223  2.32571847]
[[-0.45913466 -0.58380119 -0.36777509 -0.45562155 -0.32484155]
 [-0.36869432  0.60932841  0.29033667 -0.6390999  -0.00627141]
 [ 0.49470235  0.36994165 -0.71847152 -0.25721462 -0.18987384]
 [-0.60710583  0.38645429 -0.36419528  0.55522948 -0.20287339]
 [-0.19987986 -0.04112578 -0.3627762  -0.09757656  0.90400716]]


In [79]:
u,s,v = np.linalg.svd(np.linalg.pinv(J.T))
print(u)
print("s:",s, "1/s:", 1/s)
print(v)

[[-0.34855109  0.76617455  0.53989692]
 [-0.33849627 -0.64004021  0.68975996]
 [ 0.87403227  0.05766349  0.48243395]]
s: [2.32571847 1.5444223  0.55263755] 1/s: [0.42997466 0.6474913  1.80950425]
[[ 0.49470235  0.36994165 -0.71847152 -0.25721462 -0.18987384]
 [-0.36869432  0.60932841  0.29033667 -0.6390999  -0.00627141]
 [ 0.45913466  0.58380119  0.36777509  0.45562155  0.32484155]
 [-0.62041576  0.38226829 -0.39044045  0.54632139 -0.13432958]
 [-0.15366764 -0.0700657  -0.33436661 -0.13904639  0.91670177]]


In [82]:
u,s,v = np.linalg.svd(J.T)
print(u)
print("s:",s, "1/s:", 1/s)
print(v)

[[-0.45913466 -0.36869432  0.49470235 -0.60710583 -0.19987986]
 [-0.58380119  0.60932841  0.36994165  0.38645429 -0.04112578]
 [-0.36777509  0.29033667 -0.71847152 -0.36419528 -0.3627762 ]
 [-0.45562155 -0.6390999  -0.25721462  0.55522948 -0.09757656]
 [-0.32484155 -0.00627141 -0.18987384 -0.20287339  0.90400716]]
s: [1.80950425 0.6474913  0.42997466] 1/s: [0.55263755 1.5444223  2.32571847]
[[-0.53989692 -0.68975996 -0.48243395]
 [ 0.76617455 -0.64004021  0.05766349]
 [-0.34855109 -0.33849627  0.87403227]]


In [72]:
u.T@u1

array([[-3.33066907e-16,  6.31439345e-16,  1.00000000e+00],
       [-4.51028104e-17,  1.00000000e+00, -6.10622664e-16],
       [-1.00000000e+00, -2.32452946e-16,  1.11022302e-16]])

In [74]:
v@v1.T

array([[ 6.93889390e-18,  8.20307364e-16,  1.00000000e+00,
         5.55111512e-17, -1.11022302e-16],
       [-5.16080234e-17,  1.00000000e+00, -8.10983225e-16,
        -9.32413868e-18,  1.99493200e-17],
       [-1.00000000e+00,  7.93635990e-17, -6.93889390e-18,
         8.32667268e-16,  1.11022302e-16],
       [ 6.93889390e-16,  1.49945160e-16,  4.51028104e-17,
         9.97169454e-01,  7.51869729e-02],
       [ 5.55111512e-17, -6.67868538e-17, -2.77555756e-17,
        -7.51869729e-02,  9.97169454e-01]])